version: '1.0.{build}'

image: Visual Studio 2015

platform: 
  - Win32
  - x64

configuration:
  - Debug

# Disable the Release builds until we fix code signing
#  - Release

init:
  - cmd: git config --global core.autocrlf true
  - cmd: msbuild /version

# We need to use devenv.exe instead of the built-in call for MSBuild
# because our .sln file contains a .vdproj
# See: http://help.appveyor.com/discussions/problems/626-added-a-visual-studio-install-project-and-now-and-getting-errors-during-build
# build:
#   -  project: ./Middleware CIE.sln

build_script:
  - cmd: nuget restore "Middleware CIE.sln"
  - cmd: set DEVENV="C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.com"
  - cmd: "%DEVENV% /build \"%CONFIGURATION%|%PLATFORM%\" \"Middleware CIE.sln\""

test: off
deploy: off
